#!/bin/bash

set -e

usage() {
	echo "usage: $0 SERVER_CN [CLIENT [CONF [OUT]]]" >&2
	exit 1
}

server=$1
[ -n "$server" ] || usage

CLIENT=${2:-$(id -un)}
CONF=${3:-server-udp.conf}
OUT=${4:-client/${CLIENT}.ovpn}
remote=${REMOTE:-$server}

port=$(grep "^port " "$CONF" | cut -f 2 -d " " || true)
proto=$(grep "^proto " "$CONF" | cut -f 2 -d " " || true)
cipher=$(grep "^cipher " "$CONF" | cut -f 2 -d " " || true)
mssfix=$(grep "^mssfix " "$CONF" | cut -f 2 -d " " || true)

[ -z "$proto" ] && proto=udp
[ -z "$port" ] && port=1194
[ -z "$mssfix" ] && mssfix=1360

echo "got $CONF $port $proto $cipher -> $OUT" >&2
mkdir -p "$(dirname "$OUT")"
umask 077
rm -f "$OUT"
install -m 600 /dev/null "$OUT"
(
./subst client.ovpn.in \
	REMOTE="$remote" \
	SERVER="$server" \
	PORT="$port" \
	PROTO="$proto" \
	CIPHER="$cipher" \
	MSSFIX="$mssfix"

echo "<ca>"
sed -n '/BEGIN CERTIFICATE/,/END CERTIFICATE/p' < easy-rsa/pki/ca.crt
echo "</ca>"

echo "<cert>"
sed -n '/BEGIN CERTIFICATE/,/END CERTIFICATE/p' < easy-rsa/pki/issued/$CLIENT.crt
echo "</cert>"

echo "<key>"
sed -n '/BEGIN PRIVATE KEY/,/END PRIVATE KEY/p' < easy-rsa/pki/private/$CLIENT.key
echo "</key>"

echo "<tls-auth>"
sed -n '/BEGIN OpenVPN Static key V1/,/END OpenVPN Static key V1/p' < server/ta.key
echo "</tls-auth>"
) > "$OUT"
